version: '3'
services:
  wsgi:
    build: .
    #command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    command: gunicorn -w 3 -b 0.0.0.0:8000 rating.wsgi:application
    restart: always
    volumes:
      - ./src:/src
    #ports:
    #  - "127.0.0.1:8089:8000"
    networks:
      - rating-scraper
networks:
  rating-scraper:
