# Generated by Django 3.1 on 2021-08-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shortName', models.CharField(max_length=100)),
                ('longName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='flags',
        ),
        migrations.AddField(
            model_name='result',
            name='flags',
            field=models.ManyToManyField(to='rating.Flag'),
        ),
    ]
