# Generated by Django 3.2 on 2021-09-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20210903_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'ordering': ('-end',),
            },
        ),
        migrations.CreateModel(
            name='Basesquad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscaptain', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.team')),
            ],
            options={
                'ordering': ('-season__id',),
                'unique_together': {('season', 'team', 'player')},
            },
        ),
    ]
