# Generated by Django 3.2 on 2021-10-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_auto_20210919_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='start',
            field=models.DateField(),
        ),
    ]
