name: Scrape MAII tournaments

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python src/manage.py parse --maii
      env: 
        SECRET_KEY: ${{ secrets.SCRAPER_SECRET_KEY }}
        DATABASE_URL: ${{ secrets.SCRAPER_DATABASE_URL }}
